[build]
  bin            =             './tmp/main'
  cmd            = 'go build -o ./tmp/main ./cmd/ms-catalog'
  kill_delay     = '10s'
  
  send_interrupt = true
  stop_on_error  = true

  include_ext    = [ 'go' ]
  exclude_dir    = [ 'queries' ]
  exclude_regex  = [ '_test.go', '_mock.go' ]

[screen]
  clear_on_rebuild = true

[log]
  time = true

[misc]
  clean_on_exit = true
