include:
  - deploy/compose.base.yml

services:
  backend:
    image: ko.local/ms-catalog:latest
    ports:
      - "${INIT__ENTRY__HTTP__PORT:-8080}:\
         ${INIT__ENTRY__HTTP__PORT:-8080}"
    restart: unless-stopped
    env_file: [ .env ]
    networks: [ mains ]
    depends_on:
      postgres:
        condition: service_healthy
