// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "imidll",
            "url": "https://github.com/selfshop-dev/ms-catalog"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/selfshop-dev/ms-catalog/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/products": {
            "post": {
                "description": "Creates a new product in the catalog and returns its generated UUID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Create a new product",
                "parameters": [
                    {
                        "description": "Product payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1handler.CreateProductRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1handler.CreateProductResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON body or failed field validation",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "409": {
                        "description": "Slug already exists",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "422": {
                        "description": "Semantic validation error with per-field detail",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    }
                }
            }
        },
        "/products/active": {
            "get": {
                "description": "Returns a paginated list of active products.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "List active products",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Max items to return (1–100, default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items to skip (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1handler.GetActiveProductsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "get": {
                "description": "Returns a single product by its UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get a product by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Product UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1handler.GetProductResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID format",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    }
                }
            },
            "put": {
                "description": "Fully replaces a product's fields by its UUID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Update a product",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Product UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Product payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1handler.UpdateProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1handler.UpdateProductResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID format or JSON body",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "409": {
                        "description": "Slug already exists",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "422": {
                        "description": "Semantic validation error with per-field detail",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    }
                }
            },
            "delete": {
                "description": "Permanently deletes a product by its UUID.",
                "tags": [
                    "products"
                ],
                "summary": "Delete a product",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Product UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid UUID format",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    }
                }
            }
        },
        "/products/{id}/status": {
            "put": {
                "description": "Changes the status of a product. Allowed values: active, inactive, draft, archived.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Update status product",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Product UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1handler.UpdateStatusProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1handler.UpdateStatusProductResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID format or JSON body",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    }
                }
            }
        },
        "/products/{slug}/by-slug": {
            "get": {
                "description": "Returns a single product by its slug.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get a product by slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1handler.GetProductResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid slug",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.envelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.envelope": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "success payload; omitted on errors"
                },
                "detail": {
                    "description": "human-readable error detail; omitted on success and KindInternal",
                    "type": "string"
                },
                "extensions": {
                    "description": "validation field errors; omitted on success"
                },
                "instance": {
                    "description": "request path, e.g. \"/users/42\"",
                    "type": "string"
                },
                "meta": {
                    "description": "per-request metadata (e.g. request_id); omitted if extractor returns nil",
                    "type": "object",
                    "additionalProperties": {}
                },
                "status": {
                    "description": "HTTP status code, e.g. 404",
                    "type": "integer"
                },
                "title": {
                    "description": "HTTP status text, e.g. \"Not Found\"",
                    "type": "string"
                },
                "type": {
                    "description": "Type is the RFC-9457 problem type URI. Always \"about:blank\" —\nsignals that the status code is the primary classification.",
                    "type": "string"
                }
            }
        },
        "v1handler.CreateProductRequest": {
            "type": "object",
            "required": [
                "name",
                "slug"
            ],
            "properties": {
                "currency": {
                    "type": "string",
                    "example": "USD"
                },
                "description": {
                    "type": "string",
                    "example": "Product Description"
                },
                "display_image_url": {
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                },
                "name": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1,
                    "example": "Product Name"
                },
                "price_cents": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 10000
                },
                "short_description": {
                    "type": "string",
                    "maxLength": 256,
                    "example": "Product Short Description"
                },
                "slug": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1,
                    "example": "product-name"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "active",
                        "inactive",
                        "draft",
                        "archived"
                    ],
                    "example": "active"
                }
            }
        },
        "v1handler.CreateProductResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "v1handler.GetActiveProductsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1handler.GetProductResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "v1handler.GetProductResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "display_image_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price_cents": {
                    "type": "integer"
                },
                "short_description": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "v1handler.UpdateProductRequest": {
            "type": "object",
            "required": [
                "currency",
                "name",
                "slug"
            ],
            "properties": {
                "currency": {
                    "type": "string",
                    "example": "USD"
                },
                "description": {
                    "type": "string",
                    "example": "Product Description"
                },
                "display_image_url": {
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                },
                "name": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1,
                    "example": "Product Name"
                },
                "price_cents": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 10000
                },
                "short_description": {
                    "type": "string",
                    "maxLength": 256,
                    "example": "Product Short Description"
                },
                "slug": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1,
                    "example": "product-name"
                }
            }
        },
        "v1handler.UpdateProductResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "v1handler.UpdateStatusProductRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string",
                    "enum": [
                        "active",
                        "inactive",
                        "draft",
                        "archived"
                    ],
                    "example": "active"
                }
            }
        },
        "v1handler.UpdateStatusProductResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0-dev",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "selfshop-dev/ms-catalog API",
	Description:      "REST API для управления каталогом товаров и категорий.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
